include "base.conf"
include required(file("/opt/play/application-secrets.conf")) # Mounted by deployment

kamon.modules.graphite-reporter.enabled = no

db.default.url = ${?CONF_DB_DEFAULT_URL}

dependency.api.host = ${?CONF_DEPENDENCY_API_HOST}
dependency.www.host = ${?CONF_DEPENDENCY_WWW_HOST}

