nameOverride: "dependency-api"
fullnameOverride: "dependency-api"

service:
  nameOverride: "dependency"
  readinessFailureThreshold: 4
  readinessPeriodSeconds: 3
  readinessTimeoutSeconds: 3

team: foundation

image:
  repository: flowcommerce/dependency-api

resources:
  limits:
    memory: "2Gi"
    cpu: 1
  requests:
    memory: "2Gi"
    cpu: 0.2

jvmOpts:
  memory: 1536m
  garbageCollector: ShenandoahGC

istio:
  alb: true

deployments:
  live:
    minReplicas: 1
    maxReplicas: 1
    AWSRole: "arn:aws:iam::479720515435:role/flow-prod-eks-production-role"
    env:
      - name: "CONF_DB_DEFAULT_URL"
        value: "jdbc:postgresql://dependencydb20211217.cwdsspa5jwrg.us-east-1.rds.amazonaws.com/dependencydb?tcpKeepAlive=true"
      - name: "CONF_DB_HIKARICP_MAXIMUM_POOL_SIZE"
        value: "4"
      - name: "CONF_DB_HIKARICP_MINIMUM_IDLE"
        value: "4"
      - name: "CONF_DEPENDENCY_API_HOST"
        value: "https://dependency.api.flow.io"
      - name: "CONF_DEPENDENCY_WWW_HOST"
        value: "https://dependency.flow.io"
    rateLimit:
      perPod:
      - name: local-ratelimit
        shadow_enabled: true
        filterEnforcedPercentage: "100"
        All:
          maxTokens: "200"
          maxTokensPerFill: "200"
          tokensFillInterval: "1s"

applicationSecrets:
  paths:
    - "ssm://services/shared/jwt.salt"
    - "ssm://services/dependency/"

nodeSelector:
  karpenter/role: workers
tolerations:
  - key: "role"
    operator: "Equal"
    value: "workers"
    effect: "NoSchedule"
topologySpreadConstraints:
  schedule: "DoNotSchedule"

rolloutResource:
  enabled: false

canary:
  # Disable this to follow the default RollingUpdate Strategy
  enabled: false

datadogMonitors:
- type: trace.akka_http.request.errors-sum
  warning:
    threshold: 0.1
  alert:
    notificationTarget: '@slack-team-foundation-notifications'
    threshold: 0.25
- type: trace.akka_http.request-p95
  alert:
    notificationTarget: '@slack-team-foundation-notifications'
- type: missing-metrics
