name: Rebase Scala Steward PRs

on:
  pull_request:
    types: [closed]

jobs:
  rebase:
    runs-on: ubuntu-latest
    # Only run if the merged PR was labeled 'scala-steward'
    if: github.event.pull_request.merged == true && contains(fromJSON(toJSON(github.event.pull_request.labels)), 'scala-steward')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full history to allow rebasing

      - name: Get open Scala Steward PRs
        id: prs
        run: |
          OPEN_PRS=$(gh pr list \
            --state open \
            --label scala-steward \
            --json number,headRefName \
            | jq -r ".[] | select(.headRefName != \"${{ github.event.pull_request.head.ref }}\") | .headRefName")
          echo "prs=$OPEN_PRS" >> $GITHUB_OUTPUT

      - name: Rebase remaining PRs
        run: |
          for pr_branch in ${{ steps.prs.outputs.prs }}; do
            echo "Rebasing $pr_branch onto main"
            git fetch origin main
            git checkout $pr_branch
            if git rebase origin/main; then
              git push --force-with-lease
              echo "✅ Rebasing $pr_branch succeeded"
            else
              echo "❌ Rebasing $pr_branch failed - manual intervention required"
              git rebase --abort
            fi
          done
