name: Rebase Scala Steward PRs

on:
  pull_request:
    types: [closed]

jobs:
  rebase:
    runs-on: ubuntu-latest
    # Only run if the merged PR was labeled 'scala-steward'
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full history to allow rebasing
          persist-credentials: false

      - name: Authenticate GH CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth login --with-token <<< "$GH_TOKEN"

      - name: Get open Scala Steward PRs
        id: prs
        run: |
          OPEN_PRS=$(gh pr list \
            --state open \
            --label scala-steward \
            --json number,headRefName \
            | jq -r ".[] | select(.headRefName != \"${{ github.event.pull_request.head.ref }}\") | .headRefName")
          echo "prs=$OPEN_PRS" >> $GITHUB_OUTPUT

      - name: Rebase remaining PRs
        env:
          PR_BRANCHES: ${{ steps.prs.outputs.prs }}
        run: |
          for pr_branch in $PR_BRANCHES; do
            echo "Processing $pr_branch"
            git fetch origin main
            git checkout "$pr_branch"
          
            if git merge-base --is-ancestor origin/main HEAD; then
              echo "$pr_branch is already up-to-date"
              continue
            fi
          
            if git rebase origin/main; then
              git push --force-with-lease
              echo "✅ Rebasing $pr_branch succeeded"
            else
              echo "❌ Rebasing $pr_branch failed - manual intervention required"
              git rebase --abort
            fi
          done

